<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SD.LocalCoder.AI.Git\SD.LocalCoder.AI.Git.csproj" />
    <ProjectReference Include="..\SD.LocalCoder.AI.Model\SD.LocalCoder.AI.Model.csproj" />
  </ItemGroup>

</Project>
